prefix: D:\APPS\anaconda3\envs\bishe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy<2.0 # MediaPipe requires numpy < 2.0
    - mediapipe==0.10.14
    - opencv-python==4.10.0.84
    - scikit-learn==1.5.0
    - pandas==2.2.0
    - matplotlib==3.9.0
    - PyQt5==5.15.10
    - playsound==1.2.2
    - mysql-connector-python==8.4.0
